name = "server"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_elli = ">= 2.4.0 and < 3.0.0"

gleam_pgo = ">= 0.13.0 and < 1.0.0"
amqp = "~>3.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
gleam_json = "~>1.0.1"
wisp = ">= 0.16.0 and < 1.0.0"
uuid = ">= 1.1.8 and < 2.0.0"
youid = ">= 1.2.0 and < 2.0.0"


[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
